# Generated by Django 3.0.2 on 2020-01-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(max_length=1000)),
                ('subject', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(max_length=1000)),
                ('details', models.TextField(max_length=10000)),
                ('date', models.TextField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Email')),
            ],
        ),
    ]
